apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: project-plato
data:
  default.conf: |
    server {
        listen 5432;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
